### ISSUE TITLE
TypeError: Cannot read property '_owner' of undefined

### ISSUE THREAD

**Issue by huisom** [jakubchadim/nightmare-react-utils#1]
I userd the action .react.find('.orders-item'), and then get the following error. why?

{ TypeError: Cannot read property '_owner' of undefined
    at fn (<anonymous>:14:42)
    at javascript (<anonymous>:39:21)
    at <anonymous>:54:3
    at EventEmitter.electron.ipcRenderer.on (/electron_sample/nightmare/node_modules/_electron@1.8.4@electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/init.js:63:28)
    at emitMany (events.js:146:13)
    at EventEmitter.emit (events.js:223:7) code: -1 }

**Comment by nickdrewe** [comment]
As far as I can tell, it looks like `_owner` was removed from React somewhere around 0.13, which would break this library for future releases.
